# Generated by Django 4.2.6 on 2023-10-30 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso_logger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeelog',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('Light', 'Light'), ('Light-Medium', 'Light-Medium'), ('Medium', 'Medium'), ('Medium-Dark', 'Medium-Dark'), ('Dark', 'Dark')], max_length=20, null=True),
        ),
    ]
