# Generated by Django 4.2.6 on 2023-10-30 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('espresso_logger', '0002_alter_coffeelog_roast_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coffeelog',
            name='roast_level',
            field=models.CharField(blank=True, choices=[('LIGHT', 'Light'), ('LIGHT_MEDIUM', 'Light-Medium'), ('MEDIUM', 'Medium'), ('MEDIUM_DARK', 'Medium-Dark'), ('DARK', 'Dark')], max_length=20, null=True),
        ),
    ]
